// <auto-generated />
using System;
using CcCalendar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CcCalendar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    [Migration("20260816124947_AddFocusSessions")]
    partial class AddFocusSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CcCalendar.Core.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanUndo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Projects.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Milestones", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Projects.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Records.RecordAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkRecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkRecordId");

                    b.ToTable("RecordAttachments", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Records.RecordVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkRecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkRecordId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RecordVersions", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Records.WorkRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkRecords", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Recurrence.ExcludedOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecurrenceSeriesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecurrenceSeriesId", "OccurrenceDate")
                        .IsUnique();

                    b.ToTable("ExcludedOccurrences", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Recurrence.RecurrenceSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipHolidays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("UntilInclusive")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekdayMask")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventId")
                        .IsUnique();

                    b.ToTable("RecurrenceSeries", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Reminders.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QueuedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("TriggerAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QueuedAtUtc", "TriggerAtUtc");

                    b.HasIndex("TargetType", "TargetId", "TriggerAtUtc")
                        .IsUnique();

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Reminders.ReminderDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcknowledgedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DispatchedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SnoozedUntilUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("TriggerAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasMissed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId")
                        .IsUnique();

                    b.HasIndex("AcknowledgedAtUtc", "SnoozedUntilUtc", "DispatchedAtUtc");

                    b.ToTable("ReminderDeliveries", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Schedules.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AllDayEndExclusive")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AllDayStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CalendarEvents", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Schedules.TimeBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoItemId");

                    b.ToTable("TimeBlocks", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Todos.TodoDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependsOnTodoItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TodoItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTodoItemId");

                    b.HasIndex("TodoItemId", "DependsOnTodoItemId")
                        .IsUnique();

                    b.ToTable("TodoDependencies", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsUrgentOverride")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Todos", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Todos.TodoSubtask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TodoItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoItemId");

                    b.ToTable("TodoSubtasks", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Tools.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("FocusSessions", (string)null);
                });

            modelBuilder.Entity("CcCalendar.Core.Projects.Milestone", b =>
                {
                    b.HasOne("CcCalendar.Core.Projects.Project", null)
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CcCalendar.Core.Projects.Participant", b =>
                {
                    b.HasOne("CcCalendar.Core.Projects.Project", null)
                        .WithMany("Participants")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CcCalendar.Core.Records.RecordAttachment", b =>
                {
                    b.HasOne("CcCalendar.Core.Records.WorkRecord", null)
                        .WithMany("Attachments")
                        .HasForeignKey("WorkRecordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CcCalendar.Core.Records.RecordVersion", b =>
                {
                    b.HasOne("CcCalendar.Core.Records.WorkRecord", null)
                        .WithMany("Versions")
                        .HasForeignKey("WorkRecordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CcCalendar.Core.Records.WorkRecord", b =>
                {
                    b.HasOne("CcCalendar.Core.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CcCalendar.Core.Recurrence.ExcludedOccurrence", b =>
                {
                    b.HasOne("CcCalendar.Core.Recurrence.RecurrenceSeries", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("RecurrenceSeriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CcCalendar.Core.Recurrence.RecurrenceSeries", b =>
                {
                    b.HasOne("CcCalendar.Core.Schedules.CalendarEvent", null)
                        .WithOne()
                        .HasForeignKey("CcCalendar.Core.Recurrence.RecurrenceSeries", "CalendarEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcCalendar.Core.Reminders.ReminderDelivery", b =>
                {
                    b.HasOne("CcCalendar.Core.Reminders.Reminder", null)
                        .WithOne()
                        .HasForeignKey("CcCalendar.Core.Reminders.ReminderDelivery", "ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcCalendar.Core.Schedules.CalendarEvent", b =>
                {
                    b.HasOne("CcCalendar.Core.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CcCalendar.Core.Schedules.TimeBlock", b =>
                {
                    b.HasOne("CcCalendar.Core.Todos.TodoItem", null)
                        .WithMany()
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcCalendar.Core.Todos.TodoDependency", b =>
                {
                    b.HasOne("CcCalendar.Core.Todos.TodoItem", null)
                        .WithMany()
                        .HasForeignKey("DependsOnTodoItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CcCalendar.Core.Todos.TodoItem", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CcCalendar.Core.Todos.TodoItem", b =>
                {
                    b.HasOne("CcCalendar.Core.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CcCalendar.Core.Todos.TodoSubtask", b =>
                {
                    b.HasOne("CcCalendar.Core.Todos.TodoItem", null)
                        .WithMany("Subtasks")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CcCalendar.Core.Projects.Project", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CcCalendar.Core.Records.WorkRecord", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CcCalendar.Core.Recurrence.RecurrenceSeries", b =>
                {
                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("CcCalendar.Core.Todos.TodoItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
